version: "3.8"
services:
  backend:
    image: "enniosileno/springboot-react-fullstack:24.4.2023.20.14.42"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JASYPT_ENCRYPTOR_PASSWORD: ${PROFILE_PRIVATE_KEY}
