version: "3.8"
services:
  backend:
    image: "enniosileno/springboot-react-fullstack:1.11.2022.17.32.2"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JASYPT_ENCRYPTOR_PASSWORD: ${PROFILE_PRIVATE_KEY}
